// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylradkwueviqxrniwqrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlscmFka3d1ZXZpcXhybml3cXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODU3NjYsImV4cCI6MjA2NTA2MTc2Nn0.3RO553VHGMvkF3UQhXVpqT1smJsgApoEUihBqF4LUo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);